### ISSUE TITLE
Sort native-image arguments

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-gradle-plugin#212]
It looks like arguments need to be in a specific location for `native-image`.

```
nativeImage {
    args("-H:DashboardDump=dashboard -H:+DashboardAll")
}
```
This adds args to the front, but `native-image` ignores them. When I run the command manually with args at the end dashboard is generated.

**Comment by ilopmar** [comment]
We could always add the arguments at the end, but are we sure if that will work for all of them?

**Comment by graemerocher** [comment]
This is not an issue if the arguments are separated by a `,`:

```
args("-H:DashboardDump=dashboard", "-H:+DashboardAll")
```

**Comment by dstepanov** [comment]
The problem was that it’s not possible to add more arguments using one args call. Does it make sense to split the string?

**Comment by graemerocher** [comment]
makes sense I guess

**Comment by ilopmar** [comment]
I think we shouldn't. Why don't you want to use two arguments as a list instead of one separated by an space?


The following works when defining the `args` as a list:

```
nativeImage {
    imageName("basic-app")
    args = ["-H:+StaticExecutableWithDynamicLibC", "--verbose"]
}
```

This is the output. You can see that the flag is there and also the `--verbose` has been applied:

```
> Task :nativeImage
...

Executing [
/home/ivan/.sdkman/candidates/java/21.1.0.r8-grl/jre/bin/java \
...
...
-H:+StaticExecutableWithDynamicLibC \
...
...
]
```

We are already adding things to the args: https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/163191134e2a3d89a65764fcef7df45c1f5a4c2f/src/main/java/io/micronaut/gradle/graalvm/NativeImageTask.java#L179, https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/163191134e2a3d89a65764fcef7df45c1f5a4c2f/src/main/java/io/micronaut/gradle/graalvm/NativeImageTask.java#L188, https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/163191134e2a3d89a65764fcef7df45c1f5a4c2f/src/main/java/io/micronaut/gradle/graalvm/NativeImageTask.java#L192, and a few other places.

That `args` method comes from Gradle:

```
public T args(Object... args) {
```

**Comment by dstepanov** [comment]
I don't mind using it but putting multiple args and not realizing it's incorrect made me lost hours :-/
