### ISSUE TITLE
`application.yml` not included in native image in some cases

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-gradle-plugin#327]
### Expected Behavior

The `application.yml` file should be included in the native image.

### Actual Behaviour

The `application.yml` seems to not being included in some cases in the native image.

### Steps To Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-management-graal`
- `cd micronaut-management-graal`
- `git checkout 3.2.x`
- `sdk use java 21.3.0.r11-grl`
- `./gradlew nativeCompile`
- `./build/native/nativeCompile/management`

Send curl request `curl -v localhost:8080/info`. It returns 401. More context https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/324#issuecomment-981597224

Defining the environment varaible `export ENDPOINTS_ALL_SENSITIVE=false` and restarting the native image, makes it work.

### Environment Information

- Linux Mint 20.2
- GraalVM JDK 11 & 17

### Version

3.2.1-SNAPSHOT and Gradle plugin 3.0.0

**Comment by melix** [comment]
Ah ah, actually fixing #326 allowed me to understand this bug too, because my fix introduced the same problem as the one described here! The problem is that the GraalVM plugin resources auto-detection mechanism auto-detects resources... only if there's not a `META-INF/native-image/xxx/resources-config.json` fle already. Because the `micronaut-graal` processor actually generates this file, then resources detection is effectively disabled.
