### ISSUE TITLE
Should use Log4j 2.15.0

### ISSUE THREAD

**Issue by afigul** [micronaut-projects/micronaut-gradle-plugin#340]
### Expected Behavior

Instead of Log4J 2.x Log4j 2.15.0 should be used.

### Actual Behaviour

Log4j 2.14.x is used.

### Steps To Reproduce

clean build and watch wich version of Log4j is now in your repo cache.

### Environment Information

- JDK 11

### Version

3.2.1

**Comment by melix** [comment]
Thanks for the report. The log4j 2.14 version is brought transitively by the Shadow plugin which this plugin uses, it's not a direct dependency of this plugin. We're going to address this but in any case since this is the _build plugin_ and that a build tool _is_ an arbitrary code execution engine, there's nothing critical.
