### ISSUE TITLE
Make the -all-optimized.jar publishable

### ISSUE THREAD

**Issue by charlie-harvey** [micronaut-projects/micronaut-gradle-plugin#626]
### Feature description

Currently I do not have a way to include the `-all-optimized.jar` in what Gradle publishes to my Maven Repository.

```
tasks {
    register<Jar>("optimizedJitJarAll") {
    }
}
```
Fails. Name already exists!

```
tasks {
    named<Jar>("optimizedJitJarAll") {
    }
}
```
Fails. Can't create a task with a name that already exists.

Why does it matter? Because the task is registered lazily (I think). Because the task is registered lazily, I can't reference it in the `publishing` section.

```
publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            groupId = "$group"
            artifactId = projectBaseName
            version = version
            from(components["java"])
            artifact(tasks.optimizedJitJar.get())   // <-- Works great!
            artifact(tasks.optimizedJitJarAll.get())    // <-- Very sad!
        }
    }
}
```

I would of course rather not do any of this work at all. I would rather have the default be that this jar gets published automatically.

Thanks.

**Comment by melix** [comment]
In general, we _cannot_ do this by default, because we have absolutely no idea if it's _safe_ to do: the optimized jar is, by definition, specific to the platform it was built on, so it's not necessarily reproducible. Only the developer knows if it's safe or not. You can, however, do something similar to what we've done in [Micronaut Test Resources](https://github.com/micronaut-projects/micronaut-test-resources/blob/6a92d61a5e0eac9c7dadf5e1f337cd7ffae8467e/buildSrc/src/main/groovy/io.micronaut.build.internal.server-module.gradle#L5) to achieve what you want.

**Comment by charlie-harvey** [comment]
Is there some way to "find" the "optimizedJitJarAll" task? So I can get its output or make something depend on it?

**Comment by melix** [comment]
You can, and easiest is to wrap into an `afterEvaluate`:

```gradle
afterEvaluate {
     tasks.register("myAwesomeTask", Copy) {
          from(tasks.named("optimizedJitJarAll"))
          ...
     }
}
```

**Comment by charlie-harvey** [comment]
I wanted to add the jit.jar and the optimized-jit.jar. I can get rid of the `.get()` though. Thanks.
