### ISSUE TITLE
Make it possible to allow users to define the Micronaut BOM (in order to achieve centralized version management)

### ISSUE THREAD

**Issue by CXwudi** [micronaut-projects/micronaut-gradle-plugin#681]
### Feature description

Hi, 

Thanks for making Micronaut such a great framework with GraalVM support out of the box. 

From the Gradle Plugin implementation https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/cc84332f5635e3da7c71e81460659f41fd36ae2b/minimal-plugin/src/main/java/io/micronaut/gradle/PluginsHelper.java#L48-L60 

It looks like users are forced to either define `micronautVersion` in `gradle.properties` file or use the `micronaut {}` extension to declare the version, but I would like to declare the version in my own version catalogue in `gradle/libs.verisons.toml` or in my own `dependencies.constraints` block (which is possibly inside another custom [gradle platform](https://youtu.be/8044F5gc1dE?list=PLWQK2ZdV4Yl2k2OmC_gsjDpdIBTN0qqkE&t=208)) in order to achieve centralized version management.

So maybe one feasible solution would be using [`Configuration.defaultDependencies()`](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/Configuration.html#defaultDependencies-org.gradle.api.Action-)? (similar to the [Lombok Plugin implementation](https://github.com/freefair/gradle-plugins/blob/3709c51ac65a64fb94ae350eb08423ec8932e1eb/lombok-plugin/src/main/java/io/freefair/gradle/plugins/lombok/LombokBasePlugin.java#L23-L25)), because from the Gradle documentation, the default dependencies are only added when the configuration has no dependencies. This is perfect as the plugin do not need to worry about adding Micronaut BOM when users already added it. The only concern is if users add some other dependencies to  `MICRONAUT_BOMS_CONFIGURATION` configuration but not the Micronaut BOM. I think in this case, we could add a check and throw the exception.

**Comment by melix** [comment]
I don't think relying on `defaultDependencies` is a good idea since the result is often very random, with surprising results when a user starts adding dependencies. It does make sense to support reading `micronautVersion` from the version catalog, though. I think the only way we can reliably support this is by reading from the main `libs` catalog, for a version of a specific name, e.g `libs.micronaut.version`, so you would have to have:

```
[versions]
micronaut = "..."
```

in your catalog. Note that I am currently investigating a couple related issues:

1. [Let the user import the Micronaut platform version catalog](https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/668)
2. [Let the user override specific Micronaut modules](https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/690)

One problem is that 1. is kind of incompatible with this issue and the DSL, since if you do this, there's a chicken and egg problem (we have to read the micronaut version _before_ the catalogs are read by Gradle, and once we do so, then the version of Micronaut defined in the DSL block would be ignored).

Solution 2 is made easier with a settings plugin since the Micronaut catalog already contains version properties for all modules, which makes it trivial to override, but not everyone would use the catalog, so the PR is still needed for people who don't.

**Comment by CXwudi** [comment]
Well, maybe `defaultConfiguration` is not a good solution.

But, the real problem is that not everyone would like to use `gradle.property` or the Micronaut DSL to define the version. For example, I would like to use `micronautBoms(platform("io.micronaut:micronaut-bom:3.8.9"))` to define the version. For a more advanced usage, I can have my own Gradle platform which defines `io.micronaut:micronaut-bom:3.8.9` and then I can do `micronautBoms(platform("my.platform"))` (Which is also solution B as mentioned in [this tutorial](https://www.youtube.com/watch?v=8044F5gc1dE)), but due to the plugin implementation mentioned in https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/681#issue-1640656880, I can not apply any solution mentioned in [that tutorial](https://www.youtube.com/watch?v=8044F5gc1dE) to achieve centralized version management.

Fortunately, I found a workaround, which is to define a smaller version in DSL or `gradle.property`, and let the Gradle automatically resolve the higher version came from `micronautBoms(platform())`

I made a sample Micronaut project from Micronaut Launch and added small modification to `build.gradle.kts` to demonstrate the problem and the workaround in https://github.com/CXwudi/mn-gradle-config-sample

**Comment by melix** [comment]
> For a more advanced usage, I can have my own Gradle platform which defines io.micronaut:micronaut-bom:3.8.9 and then I can do micronautBoms(platform("my.platform"))

This shouldn't be a problem, because even if you import your own platform there would be conflict resolution between the transitive platforms, so `micronaut-bom`
Can you confirm that a solution which lets you declare `micronautVersion` in `libs.gradle.toml` be good enough for you?

**Comment by CXwudi** [comment]
> Can you confirm that a solution which lets you declare micronautVersion in libs.gradle.toml be good enough for you?

I personally use version catalog, so it is good enough for me
