### ISSUE TITLE
`micronaut-aot` cannot handle with `io.micronaut.test-resources` in multi module project

### ISSUE THREAD

**Issue by rost5000** [micronaut-projects/micronaut-gradle-plugin#815]
### Expected Behavior

Gradle build fails when `micronaut-aot` and `io.micronaut.test-resources` are applied in multi module project:
```
* What went wrong:
A problem occurred evaluating root project 'aot-bug'.
> Failed to apply plugin 'io.micronaut.aot'.
   > Configuration with name 'optimizedRuntimeClasspath' not found.

```

When I disable the plugin `io.micronaut.test-resources` the problem is solved

### Actual Behaviour

The successful build with 2 plugins in multi gradle project 

### Steps To Reproduce

1. Clone the project: https://github.com/rost5000/micronaut-aot-multiproject-bug
2. type `gradle clean build
3. You can see the error building
4. Comment 13 line in the root build.gradle
5. type `gradle clean build` and the compilation will be successfull

### Environment Information

- Java  17.0.6 (GraalVM Community 17.0.6+10-jvmci-22.3-b13)
- Windows

### Example Application

https://github.com/rost5000/micronaut-aot-multiproject-bug

### Version

4.0.5

**Comment by melix** [comment]
Thanks for the reproducer. The problem is actually not about having a multiproject build (btw I would strongly recommend you switch to convention plugins instead of using `subprojects`), but because of the use of the `library` plugin. In fact the test resources plugin was assuming that if you run Micronaut AOT, then you also use the `application` plugin. Which should be the case anyway, since AOT will do nothing for a library.
